kind: Deployment
apiVersion: apps/v1
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      name: mealie
      labels:
        app: mealie
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.4.2
          volumeMounts:
            - mountPath: /app/data
              name: mealie-data-volume
          ports:
            - containerPort: 9000
      volumes:
        - name: mealie-data-volume
          persistentVolumeClaim:
            claimName: pvc-mealie-data
