apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
