apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.211
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  type: LoadBalancer
