---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vaultwarden-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
