apiVersion: v1
kind: Service
metadata:
  labels:
    app: vaultwarden-service
  name: vaultwarden-service
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vaultwarden-service
  type: LoadBalancer
