apiVersion: v1
kind: Service
metadata:
  labels:
    app: actual-server
  name: actual-server
spec:
  ports:
  - name: web
    port: 5006
    protocol: TCP
    targetPort: 5006
  selector:
    app: actual-server
  type: LoadBalancer
