apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-adguard-data
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
