apiVersion: v1
kind: Service
metadata:
  labels:
    app: p2piano-db
  name: p2piano-db
  namespace: p2piano
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.227
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: p2piano-db
  type: LoadBalancer
