kind: Deployment
apiVersion: apps/v1
metadata:
  name: p2piano-db
  namespace: p2piano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2piano-db
  template:
    metadata:
      name: p2piano-db
      labels:
        app: p2piano-db
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: p2piano-db
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 27017
