apiVersion: v1
kind: Service
metadata:
  labels:
    app: p2piano-server
  name: p2piano-server
  namespace: p2piano
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.226
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: p2piano-server
  type: LoadBalancer
