apiVersion: v1
kind: Service
metadata:
  labels:
    app: media-server
  name: media-server
  annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.0.203
spec:
  ports:
  - name: smb
    port: 445
    protocol: TCP
    targetPort: 445
  selector:
    app: media-server
  type: LoadBalancer